# Epitaph Index
# This file serves as a registry of all videos with cataloged ad segments
# Last updated: 2025-09-07
#主要还是用json，但是toml留一份保存信息


# Schema version
schema_version = 2

# Last update timestamp in ISO 8601 format
last_updated = 2025-09-07T12:49:03+08:00

# List of videos with cataloged ad segments
# Each entry maps to a separate TOML file in the corresponding directory
videos = [
    { bvid = "BV1JDMQzUEwy", parts = 1, updated_at = 2025-09-07T12:49:03+08:00 },
    # Add more videos as they are cataloged
]

# Configuration for the Epitaph system
[config]
# Minimum confidence threshold for community-submitted segments (0.0-1.0)
min_confidence = 0.7

# Required number of unique confirmations for a segment to be included
min_confirmations = 2

# Default segment types (can be extended)
segment_types = [
    "hard_ad",
    "soft_ad",
    "sponsor_segment",
    "self_promo",
    "product_showcase"
]

# Metadata about this index
[metadata]
maintainer = "moraxborax"
repository = "https://github.com/moraxborax/21st-Century-Schizoid-Ad"
license = "MIT"

